CREATE TABLE RESTAURANT (
	RESTAURANT_ID number(6),
	NAME varchar2(1000) NOT NULL,
	ADDRESS varchar2(1000) NULL,
	PHONE_NUMBER varchar2(24) NULL,
	IMAGE_URL varchar2(1000) NULL,
	DESCRIPTION varchar2(1000) NULL,
	CATEGORY varchar2(1000) NULL,
	RATING number(3,2) NULL,
	REVIEW_COUNT number(38) NULL,
	TIME varchar2(1000) NULL,
	MINIMUM_ORDER number(5) NULL,
	STATUS varchar2(1000) NULL,
	CREATED_DATE timestamp NULL,
	UPDATED_DATE timestamp NULL
);

CREATE TABLE MENU (
	FOOD_ID number(5) NULL,
	RESTAURANT_ID number(6) NULL,
	NAME varchar2(1000) NULL,
	PHOTO_URL varchar2(1000) NULL,
	COST_PRICE number(5) NULL,
	PRICE number(6) NULL,
	STATUS varchar2(1000) NULL,
	CREATED_DATE timestamp NULL,
	UPDATED_DATE timestamp NULL
);

CREATE TABLE APP_USER (
	USER_ID varchar2(100) NOT NULL,
	NAME varchar2(1000) NULL,
	PHONE_NUMBER number(13) NULL,
	ADDRESS varchar2(1000) NULL,
	GRADE number(1) NULL,
	CREATED_DATE timestamp NULL,
	UPDATED_DATE timestamp NULL
);

CREATE TABLE APP_ORDER (
	ORDER_ID number(12) NOT NULL,
	USER_ID varchar2(100) NOT NULL,
	FOOD_ID number(5) NULL,
	RESTAURANT_ID number(6) NULL,
	QUANTITY number(2) NULL,
	PAY varchar2(100) NULL,
	REQUESTS varchar2(255) NULL,
	TOTAL number(10) NULL,
	STATUS varchar(1000) NULL,
	CREATED_DATE timestamp NULL,
	UPDATED_DATE timestamp NULL
);

CREATE TABLE CART (
	CART_ID number(6) NOT NULL,
	RESTAURANT_ID number(6) NULL,
	FOOD_ID number(5) NULL, 
	ORDER_ID number(12) NOT NULL,
	USER_ID varchar2(100) NOT NULL,
	NAME varchar2(1000) NULL,
	PHOTO_URL varchar2(1000) NULL,
	PRICE number(5) NULL, 
	QUANTITY number(2) NULL 
);

CREATE TABLE REVIEWS (
	REVIEW_ID number(24) NOT NULL, 
	USER_ID varchar2(100) NOT NULL,
	RESTAURANT_ID number(6) NULL,
	FOOD_ID number(5) NULL, 
	RATING number(1) NULL, 
	CONTENT varchar2(255) NULL, 
	REVIEW_IMG varchar2(1000) NULL,
	CREATED_DATE timestamp NULL, 
	UPDATED_DATE timestamp NULL 
);

ALTER TABLE RESTAURANT ADD CONSTRAINT PK_RESTAURANT PRIMARY KEY (
	RESTAURANT_ID
);

ALTER TABLE MENU ADD CONSTRAINT PK_MENU PRIMARY KEY (
	FOOD_ID
);

ALTER TABLE APP_USER ADD CONSTRAINT PK_USER PRIMARY KEY (
	USER_ID
);

ALTER TABLE APP_ORDER ADD CONSTRAINT PK_ORDER PRIMARY KEY (
	ORDER_ID
);

ALTER TABLE CART ADD CONSTRAINT PK_CART PRIMARY KEY (
	CART_ID
);

ALTER TABLE REVIEWS ADD CONSTRAINT PK_REVIEWS PRIMARY KEY (
	REVIEW_ID
);
